import { prisma } from '../lib/prisma.js';
import { config } from '../config.js';
import { getProvider, type AiEngine } from '../lib/ai-providers.js';

const CATEGORIES = ['comparison', 'informational', 'tutorial', 'reputation', 'authority', 'custom'] as const;

interface GeneratedTemplate {
  name: string;
  template: string;
  category: string;
}

/**
 * Uses OpenAI to generate prompt templates tailored to a workspace's brand,
 * topics and competitors. Returns an array of GeneratedTemplate objects.
 */
export async function generateAiPromptTemplates(input: {
  brandName?: string;
  topics: string[];
  competitors: string[];
  count?: number;
}): Promise<GeneratedTemplate[]> {
  // Prefer standard OpenAI key, fall back to Azure OpenAI
  const useAzure = !config.OPENAI_API_KEY && config.AZURE_OPENAI_API_KEY;
  if (!config.OPENAI_API_KEY && !config.AZURE_OPENAI_API_KEY) {
    throw new Error('No OpenAI API key configured (OPENAI_API_KEY or AZURE_OPENAI_API_KEY)');
  }

  const count = input.count ?? 15;
  const contextLines = [
    input.brandName ? `Brand: ${input.brandName}` : null,
    input.topics.length ? `Topics: ${input.topics.join(', ')}` : null,
    input.competitors.length ? `Competitors: ${input.competitors.join(', ')}` : null,
  ].filter(Boolean).join('\n');

  const systemPrompt = `You are an expert in AI search engine optimisation (AEO).
Generate ${count} diverse query prompt templates for tracking AI citation visibility.
Each template may contain these variables: {topic}, {brand}, {competitor}, {year}.
Return ONLY a valid JSON array with objects: { "name": string, "template": string, "category": "${CATEGORIES.join('|')}" }.
No markdown, no extra text, just the JSON array.`;

  const userPrompt = `Workspace context:\n${contextLines || 'General B2B SaaS brand'}\n\nGenerate ${count} prompt templates.`;

  let fetchUrl: string;
  let fetchHeaders: Record<string, string>;

  if (useAzure) {
    const endpoint = config.AZURE_OPENAI_ENDPOINT!.replace(/\/$/, '');
    const deployment = config.AZURE_OPENAI_DEPLOYMENT ?? 'gpt-4.1-mini';
    fetchUrl = `${endpoint}/openai/deployments/${deployment}/chat/completions?api-version=2024-02-01`;
    fetchHeaders = { 'Content-Type': 'application/json', 'api-key': config.AZURE_OPENAI_API_KEY! };
  } else {
    fetchUrl = 'https://api.openai.com/v1/chat/completions';
    fetchHeaders = { 'Content-Type': 'application/json', Authorization: `Bearer ${config.OPENAI_API_KEY!}` };
  }

  const res = await fetch(fetchUrl, {
    method: 'POST',
    headers: fetchHeaders,
    body: JSON.stringify({
      model: useAzure ? undefined : 'gpt-4o-mini',
      messages: [
        { role: 'system', content: systemPrompt },
        { role: 'user', content: userPrompt },
      ],
      max_tokens: 2048,
      temperature: 0.8,
    }),
  });

  if (!res.ok) throw new Error(`OpenAI API error: ${res.status} ${await res.text()}`);

  const data = await res.json() as { choices: Array<{ message: { content: string } }> };
  const raw = data.choices[0]?.message?.content ?? '[]';

  let parsed: unknown;
  try {
    // Strip possible markdown code fences
    const clean = raw.replace(/^```[a-z]*\n?/i, '').replace(/\n?```$/i, '').trim();
    parsed = JSON.parse(clean);
  } catch {
    throw new Error('AI returned invalid JSON for prompt templates');
  }

  if (!Array.isArray(parsed)) throw new Error('AI response was not a JSON array');

  return (parsed as Array<Record<string, unknown>>)
    .filter((t) => typeof t.name === 'string' && typeof t.template === 'string')
    .map((t) => ({
      name: String(t.name).trim(),
      template: String(t.template).trim(),
      category: CATEGORIES.includes(t.category as typeof CATEGORIES[number])
        ? String(t.category)
        : 'custom',
    }));
}

/**
 * Generate AI-driven prompt templates for a workspace and persist them.
 * Replaces any previously AI-generated (non-user) templates for this workspace.
 */
export async function generateAndSaveWorkspacePrompts(workspaceId: string): Promise<void> {
  const [brand, topicRows, competitorRows] = await Promise.all([
    prisma.brand.findUnique({ where: { workspaceId } }),
    prisma.topic.findMany({ where: { workspaceId }, select: { topicName: true } }),
    prisma.competitor.findMany({ where: { workspaceId }, select: { domain: true, brandName: true } }),
  ]);

  const templates = await generateAiPromptTemplates({
    brandName: brand?.name,
    topics: topicRows.map((t) => t.topicName),
    competitors: competitorRows.map((c) => c.brandName || c.domain),
  });

  // Delete previous AI-generated templates for this workspace (isSystem=false, generated by us)
  await prisma.promptTemplate.deleteMany({
    where: { workspaceId, isSystem: false },
  });

  if (templates.length > 0) {
    await prisma.promptTemplate.createMany({
      data: templates.map((t) => ({
        workspaceId,
        name: t.name,
        template: t.template,
        category: t.category,
        isSystem: false,
      })),
    });
  }
}

export async function listPromptTemplates(workspaceId: string) {
  return prisma.promptTemplate.findMany({
    where: { workspaceId },
    orderBy: [{ category: 'asc' }, { name: 'asc' }]
  });
}

export async function getPromptTemplate(id: string) {
  return prisma.promptTemplate.findUniqueOrThrow({ where: { id } });
}

export async function createPromptTemplate(input: {
  workspaceId: string;
  name: string;
  template: string;
  category?: string;
}) {
  return prisma.promptTemplate.create({
    data: {
      workspaceId: input.workspaceId,
      name: input.name,
      template: input.template,
      category: input.category || 'custom'
    }
  });
}

export async function updatePromptTemplate(id: string, workspaceId: string, input: { name?: string; template?: string; category?: string }) {
  const prompt = await prisma.promptTemplate.findUniqueOrThrow({ where: { id } });
  if (prompt.isSystem) {
    const err = new Error('Cannot modify system templates');
    (err as Error & { status: number }).status = 403;
    throw err;
  }
  if (prompt.workspaceId !== workspaceId) {
    const err = new Error('Not authorized');
    (err as Error & { status: number }).status = 403;
    throw err;
  }

  return prisma.promptTemplate.update({ where: { id }, data: input });
}

export async function deletePromptTemplate(id: string, workspaceId: string) {
  const prompt = await prisma.promptTemplate.findUniqueOrThrow({ where: { id } });
  if (prompt.isSystem) {
    const err = new Error('Cannot delete system templates');
    (err as Error & { status: number }).status = 403;
    throw err;
  }
  if (prompt.workspaceId !== workspaceId) {
    const err = new Error('Not authorized');
    (err as Error & { status: number }).status = 403;
    throw err;
  }
  await prisma.promptTemplate.delete({ where: { id } });
  return { ok: true };
}

export async function generateQueriesFromTemplates(input: {
  workspaceId: string;
  topicIds: string[];
  templateIds?: string[];
}) {
  const topics = await prisma.topic.findMany({
    where: { id: { in: input.topicIds }, workspaceId: input.workspaceId }
  });

  if (topics.length === 0) {
    return [];
  }

  const brand = await prisma.brand.findUnique({ where: { workspaceId: input.workspaceId } });
  const competitors = await prisma.competitor.findMany({ where: { workspaceId: input.workspaceId } });

  let templates;
  if (input.templateIds?.length) {
    templates = await prisma.promptTemplate.findMany({
      where: { id: { in: input.templateIds } }
    });
  } else {
    templates = await prisma.promptTemplate.findMany({
      where: { OR: [{ isSystem: true }, { workspaceId: input.workspaceId }] }
    });
  }

  const year = new Date().getFullYear().toString();
  const queries: Array<{ workspaceId: string; topicId: string; query: string; status: string }> = [];

  for (const topic of topics) {
    for (const tpl of templates) {
      let queryText = tpl.template
        .replace(/\{topic\}/g, topic.topicName)
        .replace(/\{year\}/g, year);

      if (brand) {
        queryText = queryText.replace(/\{brand\}/g, brand.name);
      }

      // Skip templates requiring competitor if none exist
      if (queryText.includes('{competitor}')) {
        if (competitors.length === 0) continue;
        for (const comp of competitors) {
          const compQuery = queryText.replace(/\{competitor\}/g, comp.brandName || comp.domain);
          queries.push({
            workspaceId: input.workspaceId,
            topicId: topic.id,
            query: compQuery,
            status: 'ACTIVE'
          });
        }
        continue;
      }

      queries.push({
        workspaceId: input.workspaceId,
        topicId: topic.id,
        query: queryText,
        status: 'ACTIVE'
      });
    }
  }

  // Deduplicate against existing queries
  const existingQueries = await prisma.aeoQuery.findMany({
    where: { workspaceId: input.workspaceId },
    select: { query: true }
  });
  const existingSet = new Set(existingQueries.map((q) => q.query.toLowerCase()));
  const newQueries = queries.filter((q) => !existingSet.has(q.query.toLowerCase()));

  if (newQueries.length > 0) {
    await prisma.aeoQuery.createMany({ data: newQueries });
  }

  return prisma.aeoQuery.findMany({
    where: { workspaceId: input.workspaceId },
    include: { topic: { select: { id: true, topicName: true } } },
    orderBy: { createdAt: 'desc' }
  });
}

export async function runPromptTemplate(input: {
  templateId: string;
  workspaceId: string;
  topicId?: string;
  variables?: Record<string, string>;
  engines: AiEngine[];
}) {
  const [template, brand, topicRow] = await Promise.all([
    prisma.promptTemplate.findUniqueOrThrow({ where: { id: input.templateId } }),
    prisma.brand.findUnique({ where: { workspaceId: input.workspaceId } }),
    input.topicId
      ? prisma.topic.findUnique({ where: { id: input.topicId } })
      : Promise.resolve(null),
  ]);

  let queryText = template.template
    .replace(/\{year\}/g, new Date().getFullYear().toString())
    .replace(/\{topic\}/g, topicRow?.topicName ?? '')
    .replace(/\{brand\}/g, brand?.name ?? '');

  if (input.variables) {
    for (const [k, v] of Object.entries(input.variables)) {
      queryText = queryText.replace(new RegExp(`\\{${k}\\}`, 'g'), v);
    }
  }

  // Upsert the query record
  let query = await prisma.aeoQuery.findFirst({
    where: { workspaceId: input.workspaceId, query: queryText }
  });
  if (!query) {
    query = await prisma.aeoQuery.create({
      data: {
        workspaceId: input.workspaceId,
        topicId: input.topicId ?? null,
        query: queryText,
        status: 'ACTIVE'
      }
    });
  }

  // Call AI providers in parallel, store each result as a QueryRun
  const results = await Promise.all(
    input.engines.map(async (engine) => {
      const provider = getProvider(engine);
      const aiResult = await provider.query(queryText);
      const run = await prisma.queryRun.create({
        data: {
          workspaceId: input.workspaceId,
          queryId: query!.id,
          engine,
          responseText: aiResult.responseText,
          status: 'COMPLETED'
        }
      });
      return {
        runId: run.id,
        engine,
        responseText: aiResult.responseText,
        citations: aiResult.citations,
        latencyMs: aiResult.latencyMs
      };
    })
  );

  return { queryText, queryId: query.id, results };
}
